using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;

namespace TableTool;

/// <summary>
/// 生成 Tables.g.cs（单文件全量重写）。
/// 约束：命名空间由调用方传入（须与读表层 ConfigTable/TableJson 同命名空间）、锁 C# 9 语法、
/// 公共字段名与 Excel/JSON 一字不差、System 类型全限定（文件不写 using）、UTF-8 无 BOM。
/// 调用形态契约（与手写核心对接，勿改）：
///   行表  → TableJson.LoadRows&lt;TKey, TRow&gt;("表名", readJson("表名"), r =&gt; r.主键字段)
///   单例  → TableJson.LoadSingleton&lt;T&gt;("表名", readJson("表名"))
/// </summary>
public static class CodeGenerator
{
    private static readonly UTF8Encoding Utf8NoBom = new(false);

    /// <summary>tables 须已按 工作簿文件名 → Sheet 顺序 排好（确定性输出）。</summary>
    public static string Generate(IReadOnlyList<TableDef> tables, string ns)
    {
        var sb = new StringBuilder();
        sb.Append("// <auto-generated/>\n");
        sb.Append("// 由 TableTool 生成：dotnet run --project Tools/TableTool -- convert（或 Unity 菜单 Tools/配表/转表）\n");
        sb.Append("// 正本是 Tables/*.xlsx，请勿手改本文件（convert 时全量重写）。\n");
        sb.Append("#pragma warning disable 0649\n");
        sb.Append("\n");
        sb.Append($"namespace {ns}\n");
        sb.Append("{\n");

        // ---- 行类 / 单例类 ----
        foreach (var t in tables)
        {
            var className = t.IsSingleton ? t.Name : t.Name + "Row";
            sb.Append($"    /// <summary>{Xml(t.Workbook)}!{Xml(t.Name)}{(t.IsSingleton ? "（单例参数组）" : "")}</summary>\n");
            sb.Append($"    public sealed class {className}\n");
            sb.Append("    {\n");
            foreach (var f in t.Fields)
            {
                if (f.Desc.Length > 0)
                    sb.Append($"        /// <summary>{Xml(f.Desc)}</summary>\n");
                sb.Append($"        public {TypeSystem.CSharpName(f.Type)} {f.Name};\n");
            }
            sb.Append("    }\n");
            sb.Append("\n");
        }

        // ---- Tables 注册表 ----
        sb.Append("    public static class Tables\n");
        sb.Append("    {\n");
        foreach (var t in tables)
        {
            if (t.IsSingleton)
                sb.Append($"        public static {t.Name} {t.Name} {{ get; private set; }}\n");
            else
                sb.Append($"        public static ConfigTable<{KeyCs(t)}, {t.Name}Row> {t.Name} {{ get; private set; }}\n");
        }
        sb.Append("\n");

        sb.Append("        public static readonly string[] AllTableNames =\n");
        sb.Append("        {\n");
        foreach (var t in tables)
            sb.Append($"            \"{t.Name}\",\n");
        sb.Append("        };\n");
        sb.Append("\n");

        sb.Append("        public static bool IsLoaded { get; private set; }\n");
        sb.Append("\n");

        sb.Append("        public static void LoadAll(System.Func<string, string> readJson)\n");
        sb.Append("        {\n");
        foreach (var t in tables)
        {
            if (t.IsSingleton)
                sb.Append($"            {t.Name} = TableJson.LoadSingleton<{t.Name}>(\"{t.Name}\", readJson(\"{t.Name}\"));\n");
            else
                sb.Append($"            {t.Name} = TableJson.LoadRows<{KeyCs(t)}, {t.Name}Row>(\"{t.Name}\", readJson(\"{t.Name}\"), r => r.{t.Fields[0].Name});\n");
        }
        sb.Append("            IsLoaded = true;\n");
        sb.Append("        }\n");
        sb.Append("    }\n");
        sb.Append("}\n");
        return sb.ToString();
    }

    public static void WriteTo(string path, IReadOnlyList<TableDef> tables, string ns)
    {
        Directory.CreateDirectory(Path.GetDirectoryName(path)!);
        File.WriteAllText(path, Generate(tables, ns), Utf8NoBom);
    }

    private static string KeyCs(TableDef t) => t.KeyType == FieldType.Int ? "int" : "string";

    private static string Xml(string s) => s.Replace("&", "&amp;").Replace("<", "&lt;").Replace(">", "&gt;");
}
